#!/bin/bash
path_real=./train_set/Celeb-real
path_fake=./train_set/Celeb-synthesis
output_path=./train_set/video_frames/videos

rm -rf ./train_set/video_frames/*
mkdir ./train_set/video_frames/videos

touch ./train_set/video_frames/train.txt
touch ./train_set/video_frames/val.txt
touch ./train_set/video_frames/test.txt

count_r=$(ls $path_real | wc -w)
count_f=$(ls $path_fake | wc -w)

count_val_r=$(echo "scale=0; 0.1*$count_r" | bc)
count_val_f=$(echo "scale=0; 0.1*$count_f" | bc)

count_val_r=$(echo ${count_val_r%.*})
count_val_f=$(echo ${count_val_f%.*})

let "count_val_r2 = count_val_r * 2"
let "count_val_f2 = count_val_f * 2"
i=0

#for real videos
for file in $(ls ${path_real} | shuf);
do
	mkdir ${output_path}/video_${i}_folder
	ffmpeg -i ${path_real}/${file} -vf "scale=-1:256" -loglevel panic -q:v 0 ${output_path}/video_${i}_folder/%05d.jpg
	
	if [ $i -lt $count_val_r ]
	then
		echo "${output_path}/video_${i}_folder 1 $(ls ${output_path}/video_${i}_folder | wc -w) 0" >> ./train_set/video_frames/val.txt
	elif [ $i -lt $count_val_r2 ]
	then
		echo "${output_path}/video_${i}_folder 1 $(ls ${output_path}/video_${i}_folder | wc -w) 0" >> ./train_set/video_frames/test.txt
	else
		echo "${output_path}/video_${i}_folder 1 $(ls ${output_path}/video_${i}_folder | wc -w) 0" >> ./train_set/video_frames/train.txt
	fi
	
	let "i = i + 1"
done

j=0

#for fake videos
for file in $(ls ${path_fake} | shuf);
do
	mkdir ${output_path}/video_${i}_folder
	ffmpeg -i ${path_fake}/${file} -vf "scale=-1:256" -loglevel panic -q:v 0 ${output_path}/video_${i}_folder/%05d.jpg
	
	if [ $j -lt $count_val_f ]
	then
		echo "${output_path}/video_${i}_folder 1 $(ls ${output_path}/video_${i}_folder | wc -w) 1" >> ./train_set/video_frames/val.txt
	elif [ $j -lt $count_val_f2 ]
	then
		echo "${output_path}/video_${i}_folder 1 $(ls ${output_path}/video_${i}_folder | wc -w) 1" >> ./train_set/video_frames/test.txt
	else
		echo "${output_path}/video_${i}_folder 1 $(ls ${output_path}/video_${i}_folder | wc -w) 1" >> ./train_set/video_frames/train.txt
	fi
	
	let "i = i + 1"
	let "j = j + 1"
done

echo "Done"


